ipbus/ipbus-firmware

- README.rst
Since the reference for the TWEPP paper begins with `C. `, it is currently interpreted as a reStructuredText list item; the C has been escaped to avoid this.
> README : Prevent paper reference being interpreted as list 

- boards/enclustra_ax3_pm3/base_fw/synth/firmware/ucf/enclustra_ax3_pm3.tcl
Patch tested successfully in external project.
> Updated pinout constrains to detect 'cfg' ports automatically. See #42

- boards/kcu105/base_fw/kcu105_basex/synth/firmware/ucf/kcu105_basex.tcl
This pull request addresses issue #62 - i.e. it removes the mention of an used clock from the KCU105 example design's async clock group declaration.
> KCU105 example design : Remove unused clock from constraints

- .gitlab-ci.yml
- boards/sim/firmware/hdl/sim_infra.vhd
- components/ipbus_util/firmware/sim_hdl/clock_sim.vhd
This pull request updates the 40MHz output clock from the sim infra to make the frequency configurable (changing port name in the process); it solves issue #72
> Update sim infra to have output clock of configurable frequency

- components/ipbus_slaves/firmware/hdl/ipbus_ctrs_ported.vhd
This pull request fixes a bug from PR #65 - omission of `READ_ONLY` generic from declaration of the `ipbus_ctrs_ported` entity. Part of issue #64
> Slave ipbus_ctrs_ported : Add missing 'READ_ONLY' generic

- .gitlab-ci.yml
- boards/zcu102/base_fw/zcu102_basex/synth/firmware/cfg/settings_ku.tcl
- boards/zcu102/base_fw/zcu102_basex/synth/firmware/cfg/zcu102_basex.dep
- boards/zcu102/base_fw/zcu102_basex/synth/firmware/cfg/zcu102_basex_infra.dep
- boards/zcu102/base_fw/zcu102_basex/synth/firmware/cfg/zu9.dep
- boards/zcu102/base_fw/zcu102_basex/synth/firmware/hdl/top_zcu102_basex.vhd
- boards/zcu102/base_fw/zcu102_basex/synth/firmware/hdl/zcu102_basex.vhd
- boards/zcu102/base_fw/zcu102_basex/synth/firmware/hdl/zcu102_basex_infra.vhd
- boards/zcu102/base_fw/zcu102_basex/synth/firmware/ucf/zcu102_basex.tcl
- components/ipbus_eth/firmware/cfg/zcu102_basex.dep
- projects/example/firmware/cfg/top_zcu102_basex.dep
- tests/ci/test_build.sh
This pull request add the ZCU102 example design that's described in issue #76 
It has been validated on the board at RAL - no errors observed in 1 billion-transaction soak test (`Validation` mode of `PerfTester.exe` from uHAL 2.6.x).
> Add ZCU102 basex example design

- components/ipbus_slaves/firmware/hdl/ipbus_dpram.vhd
- components/ipbus_slaves/firmware/hdl/ipbus_ported_dpram.vhd
This pull request fixes issue #110 - i.e. it updates the VHDL for the dual-port RAM slaves to remove the 'null range' aggregate assignment statements for which Vivado 2018.3 reports critical warnings
(*N.B.* However, as noted in issue #110, although Vivado 2018.3 reports the 'null range' aggregate assignment as a critical warning, it does not adversely affect the implementation of the dual-port RAM slaves.)
> Resolve 'null range' critical warning in Vivado 2018.3

- boards/k800/synth/firmware/hdl/k800_infra.vhd
- boards/vcu118/synth/firmware/hdl/vcu118_infra.vhd
- components/ipbus_core/firmware/hdl/ipbus_trans_decl.vhd
- components/ipbus_pcie/firmware/hdl/pcie_xdma_axi_us_if.vhd
- components/ipbus_pcie/firmware/hdl/pcie_xdma_axi_usp_if.vhd
- components/ipbus_transport_axi/firmware/hdl/ipbus_transport_axi_if.vhd
- components/ipbus_transport_udp/firmware/hdl/udp_if_flat.vhd
This pull request addresses issue #117 - i.e:
* Increases `ipbus_trans_decl.addr_width` to 16 (was 12)
* Increases address width in the AXI transport interface's BRAM controller
> Increase transactor interface's limit on packet size

- components/ipbus_core/firmware/hdl/ipbus_pipeline.vhd
This pull request should resolve issue #99 
I have performed a quick test to check that the fix in commit 729e933 resolves the issue. Specifically, I added an instance of `ipbus_pipeline` before the address decoder in `ipbus_example`. Before this change, the simulation example design would not start due to the compilation error; after this change, the simulation example design responds to transactions (both incrementing and non-incrementing) from `PerfTester.exe` without any errors.
> Fix compilation error ipbus_pipeline

- components/ipbus_util/firmware/hdl/clocks/clocks_7s_extphy.vhd
- components/ipbus_util/firmware/hdl/clocks/clocks_7s_extphy_se.vhd
- components/ipbus_util/firmware/hdl/clocks/clocks_7s_serdes.vhd
- components/ipbus_util/firmware/hdl/clocks/clocks_us_serdes.vhd
- components/ipbus_util/firmware/hdl/clocks/clocks_usp_serdes.vhd
This pull request resolves issues #127 and #128 - i.e. it:
* Updates the clocks modules to set the `clkin1_period` generic to `1000.0 / CLK_FR_FREQ`
* Updates the process generating `rsto_aux` in `clocks_us_serdes.vhd` and `clocks_usp_serdes.vhd` to use the post-buffer signal for the aux clock.
> Fix MMCM clock period typo in clocks modules

- components/ipbus_util/addr_table/ipbus_example.xml
As described in title; fixed #130
> Fix LED mask in example design address tables

- boards/enclustra_ax3_pm3/synth/firmware/cfg/enclustra_ax3_pm3_infra.dep
- boards/kc705/basex/synth/firmware/cfg/kc705_basex_infra.dep
- boards/kc705/gmii/synth/firmware/cfg/kc705_gmii_infra.dep
- boards/kcu105/basex/synth/firmware/cfg/kcu105_basex_infra.dep
- boards/sim/firmware/cfg/sim_eth_infra.dep
- boards/vcu118/sgmii/synth/firmware/cfg/vcu118_infra_sgmii.dep
- boards/zcu102/basex/synth/firmware/cfg/zcu102_basex_infra.dep
- components/ipbus_core/firmware/cfg/ipbus_core.dep
- components/ipbus_util/firmware/cfg/ipbus_ctrl.dep
This branch addresses the suggestion from issue #140, by:
* Removing `trans_arb.vhd` from the `ipbus_core` depfile (since it's not used by several designs that only use one 'transport interface' designs - e.g. the PCIe designs)
* Adding a new depfile, `ipbus_ctrl.dep` under `components/ipbus_util` that references `ipbus_ctrl.vhd` and all its dependencies
> Create depfile for ipbus_ctrl.vhd

- components/ipbus_slaves/firmware/hdl/drp_decl.vhd
- components/ipbus_slaves/firmware/hdl/ipbus_drp_bridge.vhd
- components/ipbus_slaves/firmware/hdl/ipbus_reg_types.vhd
Bumping DRP address width to 16 bits, in order to support UltraScale+ GTH/GTY.
This should settle issue #150.
Please note: as far as I can see, this change is _not_ exercised by any of the tests. This could change after adding the sysmon examples from pull request #145.
> Bumping DRP address width to 16 bits

- .gitlab-ci.yml
- components/ipbus_pcie/firmware/cgn/pcie_xdma_usp/xdma_0.xci
This branch:
* Fixes the XDMA upgrade error reported in #156 (by updating the Ultrascale+ XCI file to a copy generated by 2019.2 (the new file is compatible back to 2018.1)
* Updates the CI to use Vivado 2019.2 and 2018.3 (rather than 2018.3 & 2017.4)
> Fix Vivado 2019.2 Ultrascale+ XDMA error and update CI to use 2019.2

- components/ipbus_transport_axi/firmware/hdl/ipbus_transport_multibuffer_if.vhd
Just a tiny patch to make all port assignments obey true VHDL syntax in order to avoid Vivado producing 'critical warnings.'
> This should fix IPbus issue #164.

- ci/sim.yml
- ci/templates.yml
- components/ipbus_slaves/addr_table/ipbus_axi4lite_master.xml
- components/ipbus_slaves/addr_table/ipbus_freq_ctr.xml
- components/ipbus_util/addr_table/ipbus_device_dna_us_usp.xml
- components/ipbus_util/addr_table/ipbus_example.xml
- components/ipbus_util/addr_table/ipbus_example_xilinx_usp.xml
- components/ipbus_util/addr_table/ipbus_example_xilinx_x7.xml
- components/ipbus_util/addr_table/ipbus_icap.xml
- components/ipbus_util/addr_table/ipbus_iprog.xml
- components/ipbus_util/addr_table/ipbus_sysmon_us_ext_ref.xml
- components/ipbus_util/addr_table/ipbus_sysmon_us_int_ref.xml
- components/ipbus_util/addr_table/ipbus_sysmon_usp_ext_ref.xml
- components/ipbus_util/addr_table/ipbus_sysmon_usp_int_ref.xml
- components/ipbus_util/addr_table/ipbus_sysmon_x7.xml
- components/ipbus_util/addr_table/trans_buffer_test.xml
- components/opencores_i2c/addr_table/opencores_i2c.xml
- components/opencores_spi/addr_table/opencores_spi.xml
- tests/ctr_slaves/addr_table/ctr_slaves_tester.xml
- tests/ram_slaves/addr_table/ram_slaves_tester.xml
This pull request:
* Updates the CI config to use docker containers with uHAL v2.7.2 (which applies stricter checks when parsing address tables)
* Removes the `id` attribute from the root node of all address tables in the repo (since the `id` attribute is never used for root nodes).
> Address tables: Remove id attribute from root nodes

- components/ipbus_eth/firmware/hdl/eth_7s_sgmii.vhd
- components/ipbus_eth/firmware/hdl/eth_vc707_sgmii.vhd
This pull request supercedes #160 , which added the Ethernet discussed in issue #56
Only differences in this pull request: I've changed the entity/file name to `eth_7s_smgii` and rebased on top of latest `master` branch.
> VC707 ethernet block (with name updated)

- ci/sim.yml
- ci/templates.yml
- components/ipbus_transport_axi/firmware/cfg/ipbus_transport_axi.dep
- components/ipbus_transport_axi/firmware/cfg/ipbus_transport_axi_simtb.dep
- components/ipbus_transport_axi/firmware/cfg/tb_ipbus_transport_ram_if.dep
This PR fixes the ipbus transport axi sim
> ipbus transport axi sim

- boards/vcu118/sgmii/synth/firmware/hdl/top_vcu118_sgmii.vhd
- boards/vcu118/sgmii/synth/firmware/hdl/vcu118_infra_sgmii.vhd
> VC118 - Adding missing `rarp_select` signal

- boards/vcu118/sgmii/synth/firmware/ucf/eth.tcl
This branch is a fix from Javier Sastre for a problem with the Ethernet connection in the VCU118 SGMII design.
Description of the symptoms:
> Just when the board is programmed, FPGA starts PHY configuration and I’m able to ping the board, but just only for a few seconds. Then, I lose link and I have to reset the board.
Description of the fix:
> The constraints file boards/vcu118/sgmii/synth/firmware/ucf/eth.tcl  includes the activation of the differential termination of sgmii_rx. However, sgmii_clk diff pair is not terminated. Just after PHY configuration, this one starts sending the clk to the fpga. Because this line is not terminated, this induces reflections that degrade the clock until losing connection.
>
> I’ve included the following lines and I’ve got an stable connection:
> 
> …
> VCU118 SGMII example design: Fix termination settings of clock pins

- boards/vcu118/pcie/synth/firmware/hdl/vcu118_infra_pcie.vhd
- boards/vcu118/pcie/synth/firmware/ucf/vcu118_pcie.tcl
- components/ipbus_pcie/firmware/cfg/fix_axi_clk_freq.tcl~
- components/ipbus_pcie/firmware/cfg/ipbus_pcie_xdmaBypass_us.dep
- components/ipbus_pcie/firmware/cfg/ipbus_pcie_xdma_us.dep
- components/ipbus_pcie/firmware/cfg/ipbus_pcie_xdma_usp.dep
- components/ipbus_pcie/firmware/cgn/pcie_xdmaBypass_us/5gbps_cpll/xdma_0.xci
- components/ipbus_pcie/firmware/cgn/pcie_xdmaBypass_us/8gbps_qpll/xdma_0.xci
- components/ipbus_pcie/firmware/cgn/pcie_xdma_us/5gbps_cpll/xdma_0.xci
- components/ipbus_pcie/firmware/cgn/pcie_xdma_us/8gbps_qpll/xdma_0.xci
- components/ipbus_pcie/firmware/cgn/pcie_xdma_usp/5gbps_cpll/xdma_0.xci
- components/ipbus_pcie/firmware/cgn/pcie_xdma_usp/8gbps_qpll/xdma_0.xci
- components/ipbus_pcie/firmware/hdl/pcie_xdma_axi_us_if.vhd
- components/ipbus_pcie/firmware/hdl/pcie_xdma_bypass_axi_us_if.vhd
- components/ipbus_pcie/firmware/ucf/fix_axi_clk_freq.tcl
- components/ipbus_pcie/firmware/ucf/fix_axi_clk_freq.tcl~
These changes add a second version of the XDMA IP core. In addition to the 8 Gb/s version that requires a QPLL, there is now also a 5 Gb/s second version that is satisfied with a CPLL.
All examples have been verified to build, and both XDMA IP cores have been verified to work in third-party designs.
Since I have no access to PCIe setups corresponding to the example designs, these themselves have not explicitly been verified.
Note: two additional 'small fixes' for the PCIe example designs are included as well. Neither problem was big enough to be noticed until now, apparently.
> Add a lower-speed, CPLL-based version of the XDMA interface

- components/ipbus_slaves/firmware/cfg/ipbus_freq_ctr_adv.dep
- components/ipbus_slaves/firmware/hdl/ipbus_freq_ctr.vhd
- components/ipbus_slaves/firmware/hdl/ipbus_freq_ctr_adv.vhd
- components/ipbus_slaves/firmware/hdl/ipbus_freq_ctr_core.vhd
This is a refactorisation of merge request #217 from @jhegeman - the separate reference clock is now supported in a new entity `ipbus_freq_ctr_adv`, which has a `syncreg` rather than a plain `ctrlreg` since typically the reference clock would be unrelated to the IPbus clock.
Original description from !217:
> Recent experience shows that the exact frequency of the IPBus clock differs from board to board. This is no surprise, really, because this clock tends to be derived from PCIe, AXI, etc. clocks which are not necessarily very precise. It has a visible effect, though, on the frequencies reported by ipbus_freq_ctr, which uses the IPBus clock as reference.
> 
> The current modification adds a separate reference clock input to ipbus_freq_ctr, so that a more precise clock can be used if so …
> Frequency counter with separate reference clock

- boards/vcu118/sgmii/synth/firmware/hdl/vcu118_infra_sgmii.vhd
The frequency of the VCO clock frequency in the VCU118 SGMII infrastructure is incorrect. This leads to complaints from Vivado about:
[DRC AVAL-168] MMCM_ADV Phase shift and divide attr checks: The MMCME4_ADV cell infra/clocks/mmcm has a fractional CLKFBOUT_MULT_F value (3.333) which is not a multiple of the hardware granularity (0.125) and will be adjusted to the nearest supportable value. Please update the design to use a valid value.
This patch fixes that by correcting the MMCME4 generic values provided in the infrastructure code.
The above can be easily reproduced (using Vivado 2021.2) by building the top_vcu118_sgmii.dep example.
> Fix the oscillator clock frequency in the VCU118 SGMII infrastructure

- components/ipbus_util/addr_table/ipbus_sysmon_us_ext_ref.xml
- components/ipbus_util/addr_table/ipbus_sysmon_us_int_ref.xml
- components/ipbus_util/addr_table/ipbus_sysmon_usp_ext_ref.xml
- components/ipbus_util/addr_table/ipbus_sysmon_usp_int_ref.xml
- components/ipbus_util/addr_table/ipbus_sysmon_x7.xml
Fix a few inconsistencies in the inline documentation (in the address tables) for the sysmon components
> Fix a few inconsistencies in the inline documentation

- boards/vcu118/sgmii/synth/firmware/hdl/vcu118_infra_sgmii.vhd
Two changes:
- Bring out the 125 MHz and 300 MHz clocks.
- Change the MMCM VCO frequency such that the dividers will make an IPBus clock that is closer to the desired frequency.
> Improve the (SGMII version of the) VCU118 infrastructure code

- components/ipbus_slaves/firmware/cfg/ipbus_drp_bridge.dep
- components/ipbus_slaves/firmware/hdl/ipbus_drp_bridge.vhd
The original implementation of the ipbus_drp_bridge did not allow for a DRP clock different from the IPBus clock. This new implementation does. A generic allows one to choose at implementation time whether or not to include an IPBus clock bridge. The default values for the generic and the new DRP clock input port should ensure that this is fully backwards-compatible.
> Improve ipbus drp bridge

- components/ipbus_pcie/firmware/hdl/pcie_xdma_axi_usp_if.vhd
This just silences one more Vivado warning...
For completeness: I just noticed this message this week when using Vivado 2022.2. I'm not 100% sure if I have so far always overlooked this message, or if something has really changed with respect to previous Vivado versions.
> Fix a missing port in a component declaration

- components/ipbus_pcie/firmware/ucf/fix_axi_clk_freq.tcl
Since the XDMA IP core clock frequency issue was solved in Vivado 2023.3
> PICe XDMA IP core: Only apply clock frequency patch before Vivado 2023.2

- components/ipbus_core/firmware/cfg/ipbus_fabric_sel.dep
- components/ipbus_core/firmware/cfg/ipbus_package.dep
- components/ipbus_pcie/firmware/cfg/pcie_int_gen_msix.dep
- components/ipbus_pcie/firmware/cfg/pcie_xdma_axi_usp_if.dep
- components/ipbus_slaves/firmware/cfg/axi4lite_interface.dep
- components/ipbus_slaves/firmware/cfg/drp_decl.dep
- components/ipbus_slaves/firmware/cfg/ipbus_ported_dpram.dep
- components/ipbus_slaves/firmware/cfg/ipbus_reg_types.dep
- components/ipbus_transport_axi/firmware/cfg/ipbus_axi_decl.dep
- components/ipbus_util/firmware/cfg/cdc_reset.dep
- components/ipbus_util/firmware/cfg/clocks/clocks_usp_serdes.dep
- components/ipbus_util/firmware/cfg/ipbus_cdc_reg.dep
- components/ipbus_util/firmware/cfg/ipbus_clock_div.dep
- components/ipbus_util/firmware/cfg/led_stretcher.dep
- tests/ci/check-dep-files.sh
This is not an attempt to provide ipbb dependency files for _all_ packages and entities. It does, however, add several missing dependency files.
NOTE: The advantage of providing .dep files even for simple packages/entities is that it makes it possible to later on update the implementation (and the dependencies) without all downstream projects having to update their dependency files.
> Add some 'missing' ipbb dependency files
